= CGI's Vocabularies

This repository contains the source files of the Commission for the Management and Application of Geoscience Information (CGI)'s public vocabularies. 

All these vocabularies are presented as RDF data files that conform to the https://w3id.org/profile/vocpub[VocPub Profile] of the https://www.w3.org/TR/skos-reference/[Simple Knowledge Organization System (SKOS)]. SKOS is a taxonomy data model and VocPub is a profile mandating certain metadata and vocab structures.


== Repository Content

The vocabularies in this repository are all stored within the `vocabularies/` folder and are all published online at:

* <https://cgi.vocabs.ga.gov.au>

The `_background/` folder contains a number of ontologies that contain labels for all the properties used in the vocabularies data.

The `_scripts/` folder contains Python scripts that automatically validate and load vocabularies merged into this repository.

== License
CGI's vocabularies in this repository are licensed using the [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) licence. See the [LICENSE file](LICENSE) for the deed. 


== Contact
The CGI committee that is responsible for the publication of this information is the https://cgi-iugs.org/project/geoscienceterminology/[Geoscience Terminology Working Group (GTWG)], chaired by Mark Rattenbury. Please contact him for all content issues:

*Mark Rattenbury* +
https://cgi-iugs.org/author/mark-rattenbury/

Technical maintenance of CGI's vocabularies is performed by https://www.ga.gov.au[Geoscience Australia]. Contact the GA data manager:

*GA Data Manager* +
dataman@ga.gov.au

== Prez resources

This listing of the resources in this repository is used by the https://kurrawong.ai/products/prez/[Prez System] to display the vocabularies correctly.

|===
| Resource | Location | Notes

| Catalogue Definition | `catalogue.ttl` |
| Items | `./items/*.ttl` | Multiple ttl files
| Profile Definition | `profile.ttl` | Custom BuildingBlocks profile
| Context Resources | `../_background/*.ttl` | Multiple labels files for ontologies, licenses & agents
|===